FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf



# //docker build -t udagram-reverseproxy .

# docker tag udagram-reverseproxy brice123456789/udagram-reverseproxy //etape importante

# docker push brice123456789/udagram-reverseproxy